// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/distuurbia/PriceService/internal/model"

	protocol "github.com/distuurbia/PriceService/protocol/price"

	uuid "github.com/google/uuid"
)

// PriceServiceService is an autogenerated mock type for the PriceServiceService type
type PriceServiceService struct {
	mock.Mock
}

// AddSubscriber provides a mock function with given fields: subscriberID, selectedShares
func (_m *PriceServiceService) AddSubscriber(subscriberID uuid.UUID, selectedShares []string) error {
	ret := _m.Called(subscriberID, selectedShares)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, []string) error); ok {
		r0 = rf(subscriberID, selectedShares)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSubscriber provides a mock function with given fields: subscriberID
func (_m *PriceServiceService) DeleteSubscriber(subscriberID uuid.UUID) error {
	ret := _m.Called(subscriberID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(subscriberID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadFromStream provides a mock function with given fields: ctx
func (_m *PriceServiceService) ReadFromStream(ctx context.Context) ([]*model.Share, error) {
	ret := _m.Called(ctx)

	var r0 []*model.Share
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Share, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Share); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Share)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendToAllSubscribedChans provides a mock function with given fields: ctx
func (_m *PriceServiceService) SendToAllSubscribedChans(ctx context.Context) {
	_m.Called(ctx)
}

// SendToSubscriber provides a mock function with given fields: ctx, subscriberID
func (_m *PriceServiceService) SendToSubscriber(ctx context.Context, subscriberID uuid.UUID) ([]*protocol.Share, error) {
	ret := _m.Called(ctx, subscriberID)

	var r0 []*protocol.Share
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*protocol.Share, error)); ok {
		return rf(ctx, subscriberID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*protocol.Share); ok {
		r0 = rf(ctx, subscriberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*protocol.Share)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, subscriberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPriceServiceService creates a new instance of PriceServiceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceServiceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceServiceService {
	mock := &PriceServiceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
