// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: PriceService/protocol/price/services.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PriceServiceServiceClient is the client API for PriceServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceServiceServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (PriceServiceService_SubscribeClient, error)
}

type priceServiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceServiceServiceClient(cc grpc.ClientConnInterface) PriceServiceServiceClient {
	return &priceServiceServiceClient{cc}
}

func (c *priceServiceServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (PriceServiceService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &PriceServiceService_ServiceDesc.Streams[0], "/PriceServiceService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &priceServiceServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PriceServiceService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type priceServiceServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *priceServiceServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PriceServiceServiceServer is the server API for PriceServiceService service.
// All implementations must embed UnimplementedPriceServiceServiceServer
// for forward compatibility
type PriceServiceServiceServer interface {
	Subscribe(*SubscribeRequest, PriceServiceService_SubscribeServer) error
	mustEmbedUnimplementedPriceServiceServiceServer()
}

// UnimplementedPriceServiceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPriceServiceServiceServer struct {
}

func (UnimplementedPriceServiceServiceServer) Subscribe(*SubscribeRequest, PriceServiceService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPriceServiceServiceServer) mustEmbedUnimplementedPriceServiceServiceServer() {}

// UnsafePriceServiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceServiceServiceServer will
// result in compilation errors.
type UnsafePriceServiceServiceServer interface {
	mustEmbedUnimplementedPriceServiceServiceServer()
}

func RegisterPriceServiceServiceServer(s grpc.ServiceRegistrar, srv PriceServiceServiceServer) {
	s.RegisterService(&PriceServiceService_ServiceDesc, srv)
}

func _PriceServiceService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceServiceServiceServer).Subscribe(m, &priceServiceServiceSubscribeServer{stream})
}

type PriceServiceService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type priceServiceServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *priceServiceServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

// PriceServiceService_ServiceDesc is the grpc.ServiceDesc for PriceServiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceServiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PriceServiceService",
	HandlerType: (*PriceServiceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PriceServiceService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "PriceService/protocol/price/services.proto",
}
