// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	price_service "github.com/distuurbia/PriceService/protocol/price"
)

// PriceServiceServiceClient is an autogenerated mock type for the PriceServiceServiceClient type
type PriceServiceServiceClient struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields: ctx, in, opts
func (_m *PriceServiceServiceClient) Subscribe(ctx context.Context, in *price_service.SubscribeRequest, opts ...grpc.CallOption) (price_service.PriceServiceService_SubscribeClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 price_service.PriceServiceService_SubscribeClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *price_service.SubscribeRequest, ...grpc.CallOption) (price_service.PriceServiceService_SubscribeClient, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *price_service.SubscribeRequest, ...grpc.CallOption) price_service.PriceServiceService_SubscribeClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(price_service.PriceServiceService_SubscribeClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *price_service.SubscribeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPriceServiceServiceClient creates a new instance of PriceServiceServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriceServiceServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriceServiceServiceClient {
	mock := &PriceServiceServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
